(function(a){var e=function(){return{init:function(){a(document).on("click",".property_favorite",function(){var b=a(this).serializeArray(),c=a(this),d=a(this).closest("div").find(".xout");b.push({name:"action",value:"saveproperty_action"});b.push({name:"security",value:MDAjax.security});b.push({name:"property-id",value:a(this).data("property-id")});b.push({name:"property-feed",value:a(this).data("property-feed")});a.ajax({type:"POST",url:MDAjax.ajaxurl,data:b,dataType:"json"}).done(function(a){a.status&&
(c.toggleClass("property_favorite property_favorite_remove"),c.toggleClass("btn-default btn-primary"),c.find(".fa").toggleClass("fa-heart-o fa-heart"),d.hasClass("property_xout_remove")&&(d.toggleClass("property_xout_remove property_xout"),d.toggleClass("btn-primary btn-default"),d.find(".fa").toggleClass("fa-times-circle fa-times-circle-o")));alert(a.msg)});return!1})}}}(),f=function(){return{init:function(){a(document).on("click",".property_xout",function(){var b=a(this).serializeArray(),c=a(this),
d=a(this).closest("div").find(".favorite");b.push({name:"action",value:"xoutproperty_action"});b.push({name:"security",value:MDAjax.security});b.push({name:"property-id",value:a(this).data("property-id")});b.push({name:"property-feed",value:a(this).data("property-feed")});a.ajax({type:"POST",url:MDAjax.ajaxurl,data:b,dataType:"json"}).done(function(a){a.status&&(c.toggleClass("property_xout property_xout_remove"),c.toggleClass("btn-default btn-primary"),c.find(".fa").toggleClass("fa-times-circle-o fa-times-circle"),
d.hasClass("property_favorite_remove")&&(d.toggleClass("property_favorite_remove property_favorite"),d.toggleClass("btn-primary btn-default"),d.find(".fa").toggleClass("fa-heart fa-heart-o")));alert(a.msg)});return!1})}}}(),g=function(){return{init:function(){a(document).on("click",".property_favorite_remove",function(){var b=a(this).serializeArray(),c=a(this),d=a(this).closest("div").find(".xout");b.push({name:"action",value:"remove_property_action"});b.push({name:"security",value:MDAjax.security});
b.push({name:"property-id",value:a(this).data("property-id")});a.ajax({type:"POST",url:MDAjax.ajaxurl,data:b,dataType:"json"}).done(function(a){a.status&&(d.hasClass("property_xout_remove")&&(d.toggleClass("property_xout_remove property_xout"),d.toggleClass("btn-primary btn-default"),d.find(".fa").toggleClass("fa-times-circle fa-times-circle-o")),c.toggleClass("property_favorite_remove property_favorite"),c.toggleClass("btn-primary btn-default"),c.find(".fa").toggleClass("fa-heart fa-heart-o"));alert(a.msg)});
return!1})}}}(),h=function(){return{init:function(){a(document).on("click",".property_xout_remove",function(){var b=a(this).serializeArray(),c=a(this),d=a(this).closest("div").find(".favorite");b.push({name:"action",value:"remove_xout_property_action"});b.push({name:"security",value:MDAjax.security});b.push({name:"property-id",value:a(this).data("property-id")});a.ajax({type:"POST",url:MDAjax.ajaxurl,data:b,dataType:"json"}).done(function(a){a.status&&(d.hasClass("property_favorite_remove")&&(d.toggleClass("property_favorite_remove property_favorite"),
d.toggleClass("btn-primary btn-default"),d.find(".fa").toggleClass("fa-heart fa-heart-o")),c.toggleClass("property_xout_remove property_xout"),c.toggleClass("btn-primary btn-default"),c.find(".fa").toggleClass("fa-times-circle fa-times-circle-o"));alert(a.msg)});return!1})}}}();(function(){return{init:function(){a(".sendtofriend").text("Send").attr("disabled",!1);a(".closemodal").attr("disabled",!1);a(".frm_send_link_mail").on("submit",function(){var b=a(this).serializeArray();b.push({name:"action",
value:"sendtofriend_action"});b.push({name:"security",value:MDAjax.security});a(".sendtofriend-alert").removeClass("alert-success alert-danger");a(".sendtofriend").text("Processing..").attr("disabled",!0);a(".closemodal").attr("disabled",!0);a.ajax({type:"POST",url:MDAjax.ajaxurl,data:b,dataType:"json"}).done(function(b){b.status?(a(".sendtofriend-alert").removeClass("hide alert-danger").addClass("alert-success").html(b.msg),setTimeout(function(){a(".send-to-friend-modal").modal("hide");location.reload(!0)},
2E3)):a(".sendtofriend-alert").removeClass("hide alert-success").addClass("alert-danger").html(b.msg);a(".sendtofriend").text("Send").attr("disabled",!1);a(".closemodal").attr("disabled",!1)});return!1})}}})();a(window).load(function(){a(document).on("click",".register-open",function(b){a("#registerModal").modal("show");a("#registerModal .content-text").empty();var c=a(this).data("current-action");"undefined"!==typeof c&&(a("#registerModal .current_action").val(c),a("#registerModal .content-text").html(jQuery(".content-"+
c).html()));c=a(this).data("post");"undefined"!==typeof c&&a("#registerModal .data_post").val(c);b.preventDefault()});e.init();g.init();f.init();h.init()})})(jQuery);
